package dao.models;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

public class UsernameDAOImpl implements UsernameDAO{
	private static String url = "jdbc:oracle:thin:@dbbcrevature.cr84lpfaefq1.us-east-2.rds.amazonaws.com:1521:orcl";
	private static String username = "admin119";
	private static String password = "passWord4";

	// CRUD
	// creates a new username pasword DB, users table
	@Override
	public boolean createUAcct(Username account) {
		try (Connection conn = DriverManager.getConnection(url, username, password)) {
			PreparedStatement ps = conn.prepareStatement("INSERT INTO users (username, password) VALUES (?,?)");
			ps.setString(1, account.getUserName());
			ps.setString(2, account.getPassword());

			ps.executeUpdate();
		} catch (Exception e) {
			e.printStackTrace();
			return false;
		}
		return true;
	}

	// finds out what the new account number for this customer is, this account
	// number is autogenerated by a sequence and trigger in SQL
	@Override
	public Customer findAcctNum(String firstName, String lastName) {
		Customer cust = new Customer();
		try (Connection conn = DriverManager.getConnection(url, username, password)) {
			PreparedStatement ps = conn
					.prepareStatement("SELECT * FROM damon_accounts WHERE firstname = ? AND lastname = ?");
			ps.setString(1, firstName);
			ps.setString(2, lastName);
			ResultSet r = ps.executeQuery();
			while (r.next()) {
				cust.setAccountID(r.getInt(1));
			}

		} catch (Exception e) {
			e.printStackTrace();
		}
		return cust;
	}

	// creates a new username DB, junction table, adds username and acctID
	@Override
	public boolean createUAJunc(String userName, int accountID) {
		try (Connection conn = DriverManager.getConnection(url, username, password)) {
			PreparedStatement ps = conn.prepareStatement("INSERT INTO user_acct_junction (username, account_id) VALUES (?,?)");
			ps.setString(1, userName);
			ps.setInt(2, accountID);

			ps.executeUpdate();
		} catch (Exception e) {
			e.printStackTrace();
			return false;
		}
		return true;
	}
}
